name: Deploy to Prod

on:
  push:
    branches:
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-base.yml
    with:
      environment: prod
