name: Terraform CI/CD

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_directory: terraform
        terraform_version: 1.5.6

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up Terraform backend
      run: |
        #!/bin/bash
        RESOURCE_GROUP_NAME="terraform-backend-rg"
        STORAGE_ACCOUNT_NAME="tfststrgaccountgithubtest"
        CONTAINER_NAME="tfstate"

        echo "Creating resource group..."
        az group create --name $RESOURCE_GROUP_NAME --location "East US"

        echo "Creating storage account..."
        az storage account create \
          --name $STORAGE_ACCOUNT_NAME \
          --resource-group $RESOURCE_GROUP_NAME \
          --location "East US" \
          --sku Standard_LRS

        echo "Creating blob container..."
        az storage container create \
          --name $CONTAINER_NAME \
          --account-name $STORAGE_ACCOUNT_NAME

        echo "STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME" >> $GITHUB_ENV
        echo "CONTAINER_NAME=$CONTAINER_NAME" >> $GITHUB_ENV
    
    - name: Initialize Terraform
      working-directory: terraform
      run: terraform init

    - name: Validate Terraform
      working-directory: terraform
      run: terraform validate

    - name: Plan Terraform
      working-directory: terraform
      run: terraform plan

    - name: Apply Terraform
      working-directory: terraform
      run: terraform apply -auto-approve